<?php

namespace Database\model;

class NotificationFlows extends \Database\Model {

    public static ?string $uidPrefix = "nflw";

    protected static array $schema = [
        "uid" => "string",
        "name" => "string",
        "description" => ["type" => "text", "nullable" => true, "default" => null],
        "breakpoint" => "string",
        "status" => ["type" => "enum", "values" => ["active", "inactive", "draft"], "default" => "draft"],
        "priority" => ["type" => "integer", "default" => 100],
        "starts_at" => ["type" => "bigInteger", "nullable" => true, "default" => null],
        "ends_at" => ["type" => "bigInteger", "nullable" => true, "default" => null],
        "conditions" => ["type" => "text", "nullable" => true, "default" => null],
        "schedule_offset_days" => ["type" => "integer", "default" => 0],
        "recipient_type" => ["type" => "enum", "values" => ["user", "organisation", "location", "organisation_owner", "custom", "admin"], "default" => "user"],
        "recipient_email" => ["type" => "string", "nullable" => true, "default" => null],
        "created_by" => ["type" => "string", "nullable" => true, "default" => null],
    ];

    public static array $indexes = ["breakpoint", "status", "priority", "recipient_type", "created_by"];
    public static array $uniques = ["uid"];

    protected static array $requiredRows = [
        // =====================================================
        // USER FLOWS
        // =====================================================
        [
            "uid" => "nflw_consumer_welcome",
            "name" => "Velkommen til forbruger",
            "description" => "Sendes når en ny forbruger opretter sig efter OIDC verifikation",
            "breakpoint" => "nbp_user_registered",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_password_reset",
            "name" => "Nulstil adgangskode",
            "description" => "Sendes når bruger anmoder om at nulstille adgangskode",
            "breakpoint" => "nbp_user_password_reset",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],

        // =====================================================
        // ORDER FLOWS
        // =====================================================
        [
            "uid" => "nflw_order_contract",
            "name" => "Ordrekontrakt til forbruger (BNPL)",
            "description" => "Sendes til forbruger når en bnpl ordre er gennemført med kontrakt",
            "breakpoint" => "nbp_order_completed",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => '[{"field":"order.payment_plan","operator":"!=","value":"direct"}]',
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_order_completed_direct",
            "name" => "Ordrebekræftelse til forbruger (Betal nu)",
            "description" => "Sendes til forbruger når en ordre er gennemført",
            "breakpoint" => "nbp_order_completed",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => '[{"field":"order.payment_plan","operator":"=","value":"direct"}]',
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_merchant_order",
            "name" => "Ny ordre til forhandler",
            "description" => "Sendes til forhandler når en ny ordre modtages",
            "breakpoint" => "nbp_merchant_order_received",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "organisation_owner",
            "recipient_email" => null,
            "created_by" => null,
        ],

        // =====================================================
        // PAYMENT FLOWS
        // =====================================================
        [
            "uid" => "nflw_payment_success",
            "name" => "Betaling gennemført",
            "description" => "Sendes når en betaling gennemføres",
            "breakpoint" => "nbp_payment_successful",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_payment_failed",
            "name" => "Betaling fejlet",
            "description" => "Sendes når en betaling fejler",
            "breakpoint" => "nbp_payment_failed",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_payment_reminder_5d",
            "name" => "Betalingspåmindelse (5 dage)",
            "description" => "Sendes 5 dage før betalingsfrist",
            "breakpoint" => "nbp_payment_due_reminder",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => '[{"field":"days_until_due","operator":"=","value":5}]',
            "schedule_offset_days" => -5,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_payment_reminder_1d",
            "name" => "Betalingspåmindelse (1 dag)",
            "description" => "Sendes 1 dag før betalingsfrist",
            "breakpoint" => "nbp_payment_due_reminder",
            "status" => "active",
            "priority" => 110,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => '[{"field":"days_until_due","operator":"=","value":1}]',
            "schedule_offset_days" => -1,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_payment_overdue",
            "name" => "Forfalden betaling",
            "description" => "Sendes når betaling er forfalden",
            "breakpoint" => "nbp_payment_overdue",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 1,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],

        // =====================================================
        // RYKKER FLOWS
        // =====================================================
        [
            "uid" => "nflw_rykker_1",
            "name" => "1. rykker",
            "description" => "Første rykker - sendes ca. 7 dage efter forfald",
            "breakpoint" => "nbp_payment_rykker_1",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 7,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_rykker_2",
            "name" => "2. rykker",
            "description" => "Anden rykker - sendes ca. 14 dage efter forfald",
            "breakpoint" => "nbp_payment_rykker_2",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 14,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_rykker_final",
            "name" => "Sidste rykker / Inkassovarsel",
            "description" => "Sidste rykker før inkasso - sendes ca. 21 dage efter forfald",
            "breakpoint" => "nbp_payment_rykker_final",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 21,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_rykker_cancelled",
            "name" => "Rykker annulleret",
            "description" => "Sendes når en rykker annulleres af forretning eller admin",
            "breakpoint" => "nbp_payment_rykker_cancelled",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],

        // =====================================================
        // ORGANISATION FLOWS
        // =====================================================
        [
            "uid" => "nflw_org_invite",
            "name" => "Invitation til organisation",
            "description" => "Sendes til inviteret bruger",
            "breakpoint" => "nbp_org_member_invited",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "custom",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_merchant_joined",
            "name" => "Forhandler tilsluttet organisation",
            "description" => "Sendes når et medlem accepterer invitation",
            "breakpoint" => "nbp_org_member_joined",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_merchant_org_ready",
            "name" => "Forretningskonto klar",
            "description" => "Sendes når forretningskonto er klar til brug",
            "breakpoint" => "nbp_merchant_org_ready",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "organisation_owner",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_merchant_viva_approved",
            "name" => "Viva godkendelse",
            "description" => "Sendes når Viva godkender forretningen",
            "breakpoint" => "nbp_merchant_viva_approved",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "organisation_owner",
            "recipient_email" => null,
            "created_by" => null,
        ],

        // =====================================================
        // SYSTEM FLOWS
        // =====================================================
        [
            "uid" => "nflw_policy_update",
            "name" => "Politikopdatering",
            "description" => "Sendes når vilkår eller privatlivspolitik opdateres",
            "breakpoint" => "nbp_system_policy_updated",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],

        // =====================================================
        // REPORT FLOWS
        // =====================================================
        [
            "uid" => "nflw_weekly_report_org",
            "name" => "Ugentlig rapport (organisation)",
            "description" => "Ugentlig opsummering sendt til organisationsejere",
            "breakpoint" => "nbp_report_weekly_org",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "organisation_owner",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_weekly_report_loc",
            "name" => "Ugentlig rapport (lokation)",
            "description" => "Ugentlig opsummering sendt til lokationsansvarlige",
            "breakpoint" => "nbp_report_weekly_location",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "organisation_owner",
            "recipient_email" => null,
            "created_by" => null,
        ],

        // =====================================================
        // REFUND FLOWS
        // =====================================================
        [
            "uid" => "nflw_payment_refund_bnpl",
            "name" => "Betaling refunderet (BNPL)",
            "description" => "Sendes når en rate i en BNPL-ordre refunderes direkte",
            "breakpoint" => "nbp_payment_refunded",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => '[{"field":"order.payment_plan","operator":"!=","value":"direct"}]',
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_payment_refund_direct",
            "name" => "Betaling refunderet (direkte)",
            "description" => "Sendes når en direkte betaling refunderes",
            "breakpoint" => "nbp_payment_refunded",
            "status" => "active",
            "priority" => 90,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => '[{"field":"order.payment_plan","operator":"=","value":"direct"}]',
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_order_refund_bnpl",
            "name" => "Ordre refunderet (BNPL)",
            "description" => "Sendes når en BNPL-ordre refunderes (mindst én rate refunderet)",
            "breakpoint" => "nbp_order_refunded",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => '[{"field":"order.payment_plan","operator":"!=","value":"direct"}]',
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_order_refund_direct",
            "name" => "Ordre refunderet (direkte)",
            "description" => "Sendes når en ordre med direkte betaling refunderes",
            "breakpoint" => "nbp_order_refunded",
            "status" => "active",
            "priority" => 90,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => '[{"field":"order.payment_plan","operator":"=","value":"direct"}]',
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],

        // =====================================================
        // SUPPORT FLOWS
        // =====================================================
        [
            "uid" => "nflw_support_ticket_created",
            "name" => "Support henvendelse oprettet",
            "description" => "Notificerer admin når bruger opretter support henvendelse",
            "breakpoint" => "nbp_support_ticket_created",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "admin",
            "recipient_email" => null,
            "created_by" => null,
        ],
        [
            "uid" => "nflw_support_ticket_replied",
            "name" => "Support svar sendt",
            "description" => "Notificerer bruger når admin svarer på henvendelse",
            "breakpoint" => "nbp_support_ticket_replied",
            "status" => "active",
            "priority" => 100,
            "starts_at" => null,
            "ends_at" => null,
            "conditions" => null,
            "schedule_offset_days" => 0,
            "recipient_type" => "user",
            "recipient_email" => null,
            "created_by" => null,
        ],
    ];
    protected static array $requiredRowsTesting = [];

    public static array $encodeColumns = ["conditions"];
    public static array $encryptedColumns = [];

    public static function foreignkeys(): array {
        return [
            "breakpoint" => [NotificationBreakpoints::tableColumn('uid'), NotificationBreakpoints::newStatic()],
            "created_by" => [Users::tableColumn('uid'), Users::newStatic()],
        ];
    }
}
